# Generated by Django 3.0.6 on 2020-05-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200529_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
