# Generated by Django 3.0.6 on 2020-06-01 14:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/pictures'), upload_to=''),
        ),
    ]
