# Generated by Django 3.0.6 on 2020-06-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200601_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default-profile-picture.jpg', null=True, upload_to=''),
        ),
    ]
