# Generated by Django 3.0.6 on 2020-06-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200602_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default-profile-picture.png', null=True, upload_to=''),
        ),
    ]
