# Generated by Django 3.0.6 on 2020-05-31 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('user', models.ManyToManyField(null=True, related_name='myclass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
