# Generated by Django 3.0.6 on 2020-06-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0002_auto_20200602_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
    ]
