# Generated by Django 3.0.6 on 2020-05-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200529_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
