# Generated by Django 3.0.6 on 2020-06-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0003_auto_20200602_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
