# Generated by Django 3.0.6 on 2020-06-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0006_priority_myclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='myclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='myclass.Class'),
        ),
    ]
