# Generated by Django 3.0.6 on 2020-06-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0008_priority_mylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='mylist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
