# Generated by Django 3.0.6 on 2020-06-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0010_classgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='expiry_time',
            field=models.TimeField(null=True),
        ),
    ]
